from . import channel
from . import product_template
from . import product_product
from . import res_partner
from . import scm_entry
from . import package
from . import package_item
from . import package_secondary_address
from . import scm_entry_package_line
from . import scm_entry_item_line
from . import item_tags
from . import category
from . import campaign_type
from . import approval_category
from . import approval_request
from . import res_config_settings
