from . import channel
from . import product_template
from . import project
from . import represented_stores
from . import res_partner
from . import scm_entry
from . import selection_criteria
from . import store_regulation_entry
from . import store_regulations
from . import package
from . import package_list
from . import item
from . import item_line
from . import item_tags
from . import category
from . import campaign_type
